version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db_yg2016
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/Yu-Gutnisky-2016
      - ./data:/data
    links:
      - db_yg2016
    ports:
      - "8892:8888"
  db_yg2016:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "5306:3306"
